# nginx-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: backend
spec:
  selector:
    app: nginx-backend
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  externalIPs:
     - 10.20.190.25

