apiVersion: v1
kind: Service
metadata:
  name: loadbalaner-service
  namespace: cm-frontend
spec:
  selector:
    app: nginx
  ports:
    - port: 8000
      targetPort: 80
  type: ClusterIP
  externalIPs: 
    - 10.20.190.25
